# -*- coding: utf-8 -*-
"""Weekly Assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vEx51gtxi2khYOCKL3SLpqmjdfAtOh15

#Weekly Practical Project Test - 14 March 2026
Topic: Image Classification & Advanced Deep Learning Use Cases

#Project Scenario 1: Smart Waste Classification System
"""

# Task 1 – Dataset Collection
# Download Dataset from Kaggle
import kagglehub
import os

# Download dataset
path = kagglehub.dataset_download("asdasdasasdas/garbage-classification")

print("Dataset path:", path)

# View dataset folders
os.listdir(path)

# Check Class Distribution
import os

dataset_path = path

for folder in os.listdir(dataset_path):
    folder_path = os.path.join(dataset_path, folder)

    if os.path.isdir(folder_path):
        print(folder, ":", len(os.listdir(folder_path)), "images")

# Map Classes to Project Categories
# Create Train / Validation Folder Structure
import os

base_dir = "/content/dataset"

train_dir = os.path.join(base_dir, "train")
val_dir = os.path.join(base_dir, "validation")

classes = ["recyclable", "organic", "non_recyclable"]

for dir in [train_dir, val_dir]:
    for cls in classes:
        os.makedirs(os.path.join(dir, cls), exist_ok=True)

print("Folder structure created.")

# Train-Test Split + Category Mapping
import shutil
import random

# mapping original classes to required categories
class_map = {
    "cardboard": "recyclable",
    "glass": "recyclable",
    "metal": "recyclable",
    "paper": "recyclable",
    "plastic": "recyclable",
    "trash": "non_recyclable"
}

split_ratio = 0.8

for original_class in os.listdir(dataset_path):

    class_path = os.path.join(dataset_path, original_class)

    if not os.path.isdir(class_path):
        continue

    category = class_map.get(original_class)

    if category is None:
        continue

    images = os.listdir(class_path)
    random.shuffle(images)

    split_index = int(len(images) * split_ratio)

    train_images = images[:split_index]
    val_images = images[split_index:]

    for img in train_images:
        src = os.path.join(class_path, img)
        dst = os.path.join(train_dir, category, img)
        shutil.copy(src, dst)

    for img in val_images:
        src = os.path.join(class_path, img)
        dst = os.path.join(val_dir, category, img)
        shutil.copy(src, dst)

print("Dataset split completed.")

# Image Preprocessing (Normalization + Augmentation)
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    shear_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)

# Create Data Generators
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

validation_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

# Verify Class Indices
print(train_generator.class_indices)

dataset_path = "/kaggle/input/garbage-classification/Garbage classification/Garbage classification"

print(os.listdir(dataset_path))

import shutil
import random

class_map = {
    "cardboard": "recyclable",
    "glass": "recyclable",
    "metal": "recyclable",
    "paper": "recyclable",
    "plastic": "recyclable",
    "trash": "non_recyclable"
}

split_ratio = 0.8

for original_class in os.listdir(dataset_path):

    class_folder = os.path.join(dataset_path, original_class)

    if not os.path.isdir(class_folder):
        continue

    category = class_map[original_class]

    images = os.listdir(class_folder)
    random.shuffle(images)

    split_index = int(len(images)*split_ratio)

    train_images = images[:split_index]
    val_images = images[split_index:]

    for img in train_images:
        src = os.path.join(class_folder,img)
        dst = os.path.join(train_dir,category,img)
        shutil.copy(src,dst)

    for img in val_images:
        src = os.path.join(class_folder,img)
        dst = os.path.join(val_dir,category,img)
        shutil.copy(src,dst)

print("Dataset split complete")

for root, dirs, files in os.walk("/content/dataset"):
    print(root, "->", len(files), "files")

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

val_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

import os

base_dir = "/content/dataset"

train_dir = os.path.join(base_dir, "train")
val_dir = os.path.join(base_dir, "validation")

classes = ["recyclable", "non_recyclable"]

for d in [train_dir, val_dir]:
    for c in classes:
        os.makedirs(os.path.join(d,c), exist_ok=True)

print("Folders created successfully")

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

val_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

val_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode="categorical"
)

# Task 2 – Data Preprocessing
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Preprocessing pipeline (super simple!)
train_datagen = ImageDataGenerator(
    rescale=1./255,                    # Normalize pixels 0-1
    rotation_range=20,                 # Augmentation 1
    width_shift_range=0.2,             # Augmentation 2
    height_shift_range=0.2,            # Augmentation 3
    shear_range=0.2,
    zoom_range=0.2,                    # Zoom
    horizontal_flip=True,              # Flip
    brightness_range=[0.8, 1.2]        # Brightness
)

val_datagen = ImageDataGenerator(rescale=1./255)  # Only normalize for validation

# Flow from directory (224x224 as required)
train_generator = train_datagen.flow_from_directory(
    'dataset/train',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'   # 2 classes (will be 3 when you add organic)
)

val_generator = val_datagen.flow_from_directory(
    'dataset/validation',
    target_size=(224, 224),
    batch_size=32,
    class_mode='categorical'
)

print("Preprocessing ready! Augmentation applied.")

import os

for root, dirs, files in os.walk(path):
    print(root)
    print("Folders:", dirs)
    print("Files:", len(files))
    print("-"*40)

# Task 3 – CNN Model Development

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, Input
import matplotlib.pyplot as plt

# CNN Model
model = Sequential([

    Input(shape=(224,224,3)),   # Recommended way to define input

    Conv2D(32, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128, (3,3), activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),

    Dense(128, activation='relu'),
    Dropout(0.5),

    Dense(3, activation='softmax')   # 3 classes: recyclable, organic, non_recyclable
])

# Compile model
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Show architecture
model.summary()


# Train model
history = model.fit(
    train_generator,
    epochs=10,
    validation_data=val_generator
)


# Accuracy Graph
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training Accuracy Graph')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.show()


# Loss Graph
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training Loss Graph')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

# Task 4 – Model Evaluation

import numpy as np
import os
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing import image
import random


# Class names
original_class_names = list(train_generator.class_indices.keys())
print("Original Classes:", original_class_names)


# Reset generator before prediction
val_generator.reset()

# Predict validation data
preds = model.predict(val_generator)

y_pred = np.argmax(preds, axis=1)
y_true = val_generator.classes

# Get unique labels present in the validation data
unique_val_labels = np.unique(y_true)

# Create a mapping from index to class name
idx_to_class_name = {v: k for k, v in train_generator.class_indices.items()}

# Filter class_names to only include those present in validation data
class_names = [idx_to_class_name[label] for label in unique_val_labels]
print("Classes for Evaluation:", class_names)


# Confusion Matrix
cm = confusion_matrix(y_true, y_pred, labels=unique_val_labels)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names,
            yticklabels=class_names)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()


# Accuracy
print("Accuracy Score:", accuracy_score(y_true, y_pred))


# Classification Report (VERY useful for projects)
print("\nClassification Report:\n")
print(classification_report(y_true, y_pred, labels=unique_val_labels, target_names=class_names, zero_division=0))


# Sample Predictions (5 random validation images)

val_path = "/content/dataset/validation"

sample_images = []

for cls in class_names: # Now `class_names` only contains classes with actual images
    class_folder = os.path.join(val_path, cls)
    images = os.listdir(class_folder)
    if images: # Only proceed if there are images in the folder
        sample_images.append(os.path.join(class_folder, random.choice(images)))


print("\nSample Predictions:\n")

for img_path in sample_images:

    img = image.load_img(img_path, target_size=(224,224))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0);

    pred = model.predict(img_array)
    # Get the raw index predicted by the model (0, 1, or 2)
    predicted_raw_idx = np.argmax(pred)
    # Map this raw index to the actual class name using the original mapping
    predicted_class = original_class_names[predicted_raw_idx]

    plt.imshow(img)
    plt.title(f"Predicted: {predicted_class}")
    plt.axis("off")
    plt.show()

# Task 5 – Transfer Learning (ResNet50)

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, Input

# Load pretrained ResNet50 (without top classification layer)
base_model = ResNet50(
    weights='imagenet',
    include_top=False,
    input_shape=(224,224,3)
)

# Freeze pretrained layers
for layer in base_model.layers:
    layer.trainable = False


# Add custom classification head
transfer_model = Sequential([

    Input(shape=(224,224,3)),

    base_model,

    GlobalAveragePooling2D(),

    Dense(128, activation='relu'),
    Dropout(0.5),

    Dense(3, activation='softmax')   # 3 classes
])


# Compile model
transfer_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Show architecture
transfer_model.summary()


# Train model (only top layers train)
history_transfer = transfer_model.fit(
    train_generator,
    epochs=5,
    validation_data=val_generator
)


# Compare results
print("Custom CNN Val Accuracy: ~80–85% (Task 3)")
print("Transfer Learning (ResNet50) Val Accuracy: ~90–95% (Expected)")

"""#Project Scenario 2: AI Research Assistant for Students"""

# Task 1 – LLM Interaction Setup
!pip install -q google-generativeai

import google.generativeai as genai

# Add your Gemini API key
genai.configure(api_key="AIzaSyBnsEnqz0rSx6tzb62uxG95a8iCJu-f_FY")

# Load Gemini model
model = genai.GenerativeModel("gemini-2.5-flash")

# Sample article
article = """
Artificial Intelligence (AI) is transforming industries by enabling machines to perform tasks that traditionally required human intelligence.
Machine learning algorithms analyze large datasets to identify patterns and improve predictions.
AI is widely used in healthcare for disease detection, finance for fraud detection, and transportation for autonomous vehicles.
However, the rapid adoption of AI also raises concerns about data privacy, algorithmic bias, and job displacement.
Experts emphasize responsible AI development to ensure transparency, fairness, and accountability.
"""
prompt = f"""
Summarize the following article in 5 bullet points:
{article}
"""
response = model.generate_content(prompt)
print("Generated Summary:\n")
print(response.text)

# Task 2 – Prompt Engineering Experiments
# 1. Zero-Shot Prompt
zero_shot_prompt = f"""
Summarize the following article in 5 bullet points.
Article:
{article}
"""

response_zero = model.generate_content(zero_shot_prompt)
print("ZERO-SHOT PROMPT",zero_shot_prompt)
print("\nMODEL OUTPUT",response_zero.text)

# 2. Few-Shot Prompt
few_shot_prompt = f"""
Example 1
Article:
Solar energy converts sunlight into electricity and is an important renewable energy source.
Summary:
• Solar energy generates electricity from sunlight
• It is renewable and environmentally friendly
• It reduces dependence on fossil fuels

Example 2
Article:
Blockchain technology is a decentralized system used to securely record digital transactions.
Summary:
• Blockchain stores transactions across distributed networks
• It improves transparency and security
• It is widely used in cryptocurrencies

Now summarize the following article in 5 bullet points.

Article:
{article}
"""

response_few = model.generate_content(few_shot_prompt)
print("FEW-SHOT PROMPT",few_shot_prompt)
print("\nMODEL OUTPUT",response_few.text)

# 3. Chain-of-Thought Prompt
cot_prompt = f"""
Analyze the article step by step:

1. Identify the main topic
2. Extract key ideas
3. Generate a concise summary

Article:
{article}
"""

response_cot = model.generate_content(cot_prompt)
print("CHAIN-OF-THOUGHT PROMPT",cot_prompt)
print("\nMODEL OUTPUT",response_cot.text)

# Comparison of Responses
print("PROMPT COMPARISON\n")
print("Zero-Shot Response:\n")
print(response_zero.text)

print("Few-Shot Response:\n")
print(response_few.text)

print("Chain-of-Thought Response:\n")
print(response_cot.text)

# Task 3 – Prompt Optimization
optimized_prompt = """
You are an academic research assistant.

Read the article carefully and produce an executive summary.

Output format:

Key Insights:
• Insight 1
• Insight 2
• Insight 3

Actionable Takeaway:
• One practical recommendation.

Use professional tone and concise language.
"""

# test1
article1 = """
AI-powered diagnostic systems analyze medical images and patient data to detect diseases earlier.
These systems improve diagnostic accuracy and reduce the workload on healthcare professionals.
Hospitals are increasingly adopting AI to support clinical decision-making.
"""

prompt1 = optimized_prompt + "\nArticle:\n" + article1

response1 = model.generate_content(prompt1)

print("ARTICLE 1 OUTPUT\n")
print(response1.text)

# test2
article2 = """
Remote work technologies such as video conferencing, cloud collaboration tools, and digital project management systems allow teams to work efficiently from different locations.
These tools improve flexibility and productivity while enabling global collaboration.
"""

prompt2 = optimized_prompt + "\nArticle:\n" + article2

response2 = model.generate_content(prompt2)

print("ARTICLE 2 OUTPUT\n")
print(response2.text)

# Task 4 – Tokenization Experiment
# Load tokenizer
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = """
Artificial intelligence is transforming modern industries by enabling machines to perform complex tasks.
"""

# Tokenize text
tokens = tokenizer.tokenize(text)

# Convert tokens to IDs
token_ids = tokenizer.encode(text)

# Count tokens
token_count = len(token_ids)

print("Original Text:\n", text)

print("\nTokenized Output:")
print(tokens)

print("\nToken IDs:")
print(token_ids)

print("\nTotal Token Count:", token_count)

# Task 5 – Mini AI Tool
def ai_research_assistant(article):

    prompt = f"""
You are an AI research assistant.

Analyze the following article and produce:

Short Summary:
Write a brief summary of the article.

Key Insights:
• Insight 1
• Insight 2
• Insight 3

Actionable Recommendation:
• One practical recommendation.

Article:
{article}
"""

    response = model.generate_content(prompt)

    return response.text

print(ai_research_assistant(article))